n = str(input('Digite seu nome completo: ')).strip().title()
nome = n.split()
print('Muito prazer em te conhecer!')
print('Seu primeiro nome e: {}'.format(nome[0]))
print('Seu último nome e: {}'.format(nome[-1]))
#print('Seu último nome e: {}'.format(nome[len(nome)-1]))
